// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/data/models/country_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7484034086495310549),
    name: 'CountryModel',
    lastPropertyId: const obx_int.IdUid(12, 942920583761018115),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2180141570121903942),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1871693673897217449),
        name: 'code',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6663108256094463810),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9148959978872473000),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8636690531040798009),
        name: 'flagUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3002122727722076665),
        name: 'capital',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 936800385283603147),
        name: 'region',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2117185850314734038),
        name: 'population',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3173073383563973560),
        name: 'languages',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4174059320247431963),
        name: 'currencies',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1964837440999175321),
        name: 'timezones',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2961586638504958659),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 942920583761018115),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7484034086495310549),
    lastIndexId: const obx_int.IdUid(1, 6663108256094463810),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CountryModel: obx_int.EntityDefinition<CountryModel>(
      model: _entities[0],
      toOneRelations: (CountryModel object) => [],
      toManyRelations: (CountryModel object) => {},
      getId: (CountryModel object) => object.id,
      setId: (CountryModel object, int id) {
        object.id = id;
      },
      objectToFB: (CountryModel object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final nameOffset = fbb.writeString(object.name);
        final flagUrlOffset = fbb.writeString(object.flagUrl);
        final capitalOffset = fbb.writeString(object.capital);
        final regionOffset = fbb.writeString(object.region);
        final languagesOffset = fbb.writeList(
          object.languages.map(fbb.writeString).toList(growable: false),
        );
        final currenciesOffset = fbb.writeList(
          object.currencies.map(fbb.writeString).toList(growable: false),
        );
        final timezonesOffset = fbb.writeList(
          object.timezones.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, flagUrlOffset);
        fbb.addOffset(4, capitalOffset);
        fbb.addOffset(5, regionOffset);
        fbb.addInt64(6, object.population);
        fbb.addOffset(7, languagesOffset);
        fbb.addOffset(8, currenciesOffset);
        fbb.addOffset(9, timezonesOffset);
        fbb.addFloat64(10, object.latitude);
        fbb.addFloat64(11, object.longitude);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final flagUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final capitalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final populationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final languagesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final currenciesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final timezonesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object = CountryModel(
          id: idParam,
          code: codeParam,
          name: nameParam,
          flagUrl: flagUrlParam,
          capital: capitalParam,
          region: regionParam,
          population: populationParam,
          languages: languagesParam,
          currencies: currenciesParam,
          timezones: timezonesParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CountryModel] entity fields to define ObjectBox queries.
class CountryModel_ {
  /// See [CountryModel.id].
  static final id = obx.QueryIntegerProperty<CountryModel>(
    _entities[0].properties[0],
  );

  /// See [CountryModel.code].
  static final code = obx.QueryStringProperty<CountryModel>(
    _entities[0].properties[1],
  );

  /// See [CountryModel.name].
  static final name = obx.QueryStringProperty<CountryModel>(
    _entities[0].properties[2],
  );

  /// See [CountryModel.flagUrl].
  static final flagUrl = obx.QueryStringProperty<CountryModel>(
    _entities[0].properties[3],
  );

  /// See [CountryModel.capital].
  static final capital = obx.QueryStringProperty<CountryModel>(
    _entities[0].properties[4],
  );

  /// See [CountryModel.region].
  static final region = obx.QueryStringProperty<CountryModel>(
    _entities[0].properties[5],
  );

  /// See [CountryModel.population].
  static final population = obx.QueryIntegerProperty<CountryModel>(
    _entities[0].properties[6],
  );

  /// See [CountryModel.languages].
  static final languages = obx.QueryStringVectorProperty<CountryModel>(
    _entities[0].properties[7],
  );

  /// See [CountryModel.currencies].
  static final currencies = obx.QueryStringVectorProperty<CountryModel>(
    _entities[0].properties[8],
  );

  /// See [CountryModel.timezones].
  static final timezones = obx.QueryStringVectorProperty<CountryModel>(
    _entities[0].properties[9],
  );

  /// See [CountryModel.latitude].
  static final latitude = obx.QueryDoubleProperty<CountryModel>(
    _entities[0].properties[10],
  );

  /// See [CountryModel.longitude].
  static final longitude = obx.QueryDoubleProperty<CountryModel>(
    _entities[0].properties[11],
  );
}
