const availableTravelInterests = [
  {'emoji': '🏖️', 'title': 'Beach'},
  {'emoji': '🏔️', 'title': 'Adventure'},
  {'emoji': '🎭', 'title': 'Culture'},
  {'emoji': '🍜', 'title': 'Food'},
  {'emoji': '🌃', 'title': 'Nightlife'},
  {'emoji': '🌲', 'title': 'Nature'},
  {'emoji': '🛍️', 'title': 'Shopping'},
  {'emoji': '🏛️', 'title': 'History'},
];

const Map<String, List<String>> interestCountryMap = {
  'Beach': [
    'Greece',
    'Thailand',
    'Maldives',
    'Spain',
    'Australia',
    'Indonesia',
    'Mexico',
  ],
  'Adventure': [
    'Nepal',
    'Peru',
    'New Zealand',
    'Canada',
    'Chile',
    'South Africa',
  ],
  'Culture': [
    'Italy',
    'Japan',
    'Egypt',
    'India',
    'France',
    'Turkey',
    'Morocco',
  ],
  'Food': ['Italy', 'Japan', 'Mexico', 'France', 'Thailand', 'Spain'],
  'Nightlife': ['USA', 'Spain', 'Netherlands', 'Thailand', 'Germany', 'Brazil'],
  'Nature': [
    'Iceland',
    'Switzerland',
    'Canada',
    'Norway',
    'New Zealand',
    'Costa Rica',
  ],
  'Shopping': ['USA', 'UAE', 'Singapore', 'France', 'Japan', 'UK'],
  'History': [
    'Greece',
    'Italy',
    'Egypt',
    'China',
    'Turkey',
    'United Kingdom',
    'Iran',
  ],
};
